// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

#[tauri::command]
fn open_folder(path: String) -> Result<(), String> {
    tauri::api::shell::open(&path, None)
        .map_err(|e| format!("Failed to open folder: {}", e))
}

#[tauri::command] 
fn open_whatsapp(phone: String, message: Option<String>) -> Result<(), String> {
    let url = if let Some(msg) = message {
        format!("https://wa.me/{}?text={}", phone, urlencoding::encode(&msg))
    } else {
        format!("https://wa.me/{}", phone)
    };
    
    tauri::api::shell::open(&url, None)
        .map_err(|e| format!("Failed to open WhatsApp: {}", e))
}

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![open_folder, open_whatsapp])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
