[package]
name = "project-manager-pro"
version = "1.0.0"
description = "אפליקציית ניהול פרויקטים מתקדמת"
authors = ["Project Manager Team"]
license = "MIT"
repository = ""
default-run = "project-manager-pro"
edition = "2021"
rust-version = "1.70"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0", features = ["macos-private-api"] }
tauri-plugin-dialog = "2.0"
tauri-plugin-shell = "2.0"
tauri-plugin-fs = "2.0"
tauri-plugin-opener = "2.0"
dirs = "5.0"
[features]
custom-protocol = [ "tauri/custom-protocol" ]
