// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvcjnleomsimakpudykm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2Y2pubGVvbXNpbWFrcHVkeWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTIxMTUsImV4cCI6MjA3MTAyODExNX0.Hr5u_v4TOyQjwTEyilz0mPDTuWzgY0LYuUkOCMxvm-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});